export const SOURCES = {
  googleTechnical: {
    id: "googleTechnical",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Google Search technical requirements",
    url: "https://developers.google.com/search/docs/essentials/technical",
    summary: "Googlebotがブロックされず、ページがHTTP 200で応答し、インデックス可能な内容を持つことを最低技術要件として説明しています。",
  },
  googleRobots: {
    id: "googleRobots",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Robots.txt Introduction and Guide",
    url: "https://developers.google.com/search/docs/crawling-indexing/robots/intro",
    summary: "robots.txtはクローラーがリクエストできるURLを管理します。インデックス削除の手段ではありません。",
  },
  googleRobotsSpec: {
    id: "googleRobotsSpec",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "How Google interprets the robots.txt specification",
    url: "https://developers.google.com/crawling/docs/robots-txt/robots-txt-spec",
    summary: "Googlebot向けグループの選択、Allow・Disallowの一致、robots.txtのHTTPステータス処理を説明しています。",
  },
  googleCrawlerAgents: {
    id: "googleCrawlerAgents",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Googlebot",
    url: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    summary: "スマートフォン版とパソコン版が共通して使用するrobots.txt製品トークンGooglebotを説明しています。",
  },
  googleRobotsMeta: {
    id: "googleRobotsMeta",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Robots meta tag and X-Robots-Tag specifications",
    url: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag",
    summary: "meta robotsとX-Robots-Tagで、ページ単位のインデックスやスニペット表示を制御する仕様です。",
  },
  googleTitle: {
    id: "googleTitle",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Influencing title links in Google Search",
    url: "https://developers.google.com/search/docs/appearance/title-link",
    summary: "title要素やページ上の主見出しなど、検索結果のタイトルリンク生成に使われる情報と改善指針です。",
  },
  googleSnippet: {
    id: "googleSnippet",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Control your snippets in search results",
    url: "https://developers.google.com/search/docs/appearance/snippet",
    summary: "Googleはページ本文を中心にスニペットを生成し、適切な場合はmeta descriptionも利用します。固定文字数上限はありません。",
  },
  googleCanonical: {
    id: "googleCanonical",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "How to specify a canonical URL",
    url: "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls",
    summary: "重複・類似URLの代表URLをGoogleに伝える方法と、canonicalシグナルを揃える指針です。",
  },
  googleLinks: {
    id: "googleLinks",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "SEO link best practices for Google",
    url: "https://developers.google.com/search/docs/crawling-indexing/links-crawlable",
    summary: "Googleがクロールできるリンクの形式と、内容が伝わるアンカーテキストの書き方を説明しています。",
  },
  googleImages: {
    id: "googleImages",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Google image SEO best practices",
    url: "https://developers.google.com/search/docs/appearance/google-images",
    summary: "Googleが画像の内容を理解するうえで、周辺文脈、ファイル名、altテキストを利用することを説明しています。",
  },
  googleMobile: {
    id: "googleMobile",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Mobile-first indexing best practices",
    url: "https://developers.google.com/search/docs/crawling-indexing/mobile/mobile-sites-mobile-first-indexing",
    summary: "Googleはモバイル版の内容をインデックスとランキングに使用し、レスポンシブデザインを推奨しています。",
  },
  googleStructuredData: {
    id: "googleStructuredData",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "General structured data guidelines",
    url: "https://developers.google.com/search/docs/appearance/structured-data/sd-policies",
    summary: "構造化データがリッチリザルト対象になるための技術・品質ガイドラインです。表示は保証されません。",
  },
  googleUrlStructure: {
    id: "googleUrlStructure",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "URL structure best practices for Google Search",
    url: "https://developers.google.com/search/docs/crawling-indexing/url-structure",
    summary: "クロールしやすく理解しやすいURL構造と、フラグメントによるコンテンツ切り替えを避ける指針です。",
  },
  googleHreflang: {
    id: "googleHreflang",
    publisher: "Google Search Central",
    kind: "Google公式",
    title: "Tell Google about localized versions of your page",
    url: "https://developers.google.com/search/docs/specialty/international/localized-versions",
    summary: "多言語・多地域ページのhreflang指定方法と、完全修飾URLや相互参照などの要件です。",
  },
  ahrefsTitle: {
    id: "ahrefsTitle",
    publisher: "Ahrefs",
    kind: "海外SEO企業",
    title: "What Are Title Tags? How To Write Them for SEO",
    url: "https://ahrefs.com/blog/title-tag-seo/",
    summary: "検索結果での省略可能性を抑える業界上の目安として、簡潔なtitleを推奨しています。",
  },
  ahrefsMeta: {
    id: "ahrefsMeta",
    publisher: "Ahrefs",
    kind: "海外SEO企業",
    title: "How to Write the Perfect Meta Description",
    url: "https://ahrefs.com/blog/meta-description/",
    summary: "titleを補完し、検索意図と内容に合うmeta descriptionを作る実務指針です。",
  },
  ahrefsAudit: {
    id: "ahrefsAudit",
    publisher: "Ahrefs",
    kind: "海外SEO企業",
    title: "How to Do a Website Audit",
    url: "https://ahrefs.com/blog/website-audit/",
    summary: "技術・オンページ・コンテンツの監査項目と、課題を優先順位づけする実務手順です。",
  },
  semrushTechnical: {
    id: "semrushTechnical",
    publisher: "Semrush",
    kind: "海外SEO企業",
    title: "How to Perform a Technical SEO Audit",
    url: "https://www.semrush.com/blog/technical-seo-audit/",
    summary: "クロール、インデックス、canonicalなどを含む技術SEO監査の実務ガイドです。",
  },
};

export function getSources(ids = Object.keys(SOURCES)) {
  return ids.map((id) => SOURCES[id]).filter(Boolean);
}
